config/routes.rb
Rails.application.routes.draw do
  root "questions#index"

  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end

  resources :answers, only: [:show, :update]

  resources :sessions, only: [:create, :destroy]
  get "auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  # validates :body,
  #   length: {minimum: 50}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers

  validates :title,
    presence: true
    # length: {minimum: 20}

  validates :description,
    presence: true
    # length: {minimum: 50}
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

    find_or_create_by(provider: provider, uid: uid) do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
      user.oauth_token = auth.credentials.token
    end
  end

  has_many :questions

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params["question_id"])
    @answer.question = @question
    if @answer.save
      redirect_to @question
    else
      @answers = @question.answers
      @user = @question.user
      render :template => "questions/show"
    end
  end

  def update
    @answer = Answer.update(params[:id], {accepted: true})
    if @answer.save
      flash[notice] = "Answer accepted"
      redirect_to @answer.question
    else
      flash[notice] = "Answer not accepted"
      redirect_to @answer.question
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(:created_at)
    @answer = Answer.new
    if @answers.any?{|a| a[:accepted] == true}
      @selected_answer = @answers.find{|a| a[:accepted] == true}
      @answers = @question.answers.where(accepted: false)
    end
    @user = @question.user
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.update(params[:id], question_params)
    if @question.save
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @answers = @question.answers
    @question.destroy
    @answers.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_or_create_from_omniauth(request.env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, fenced_code_blocks: true, disable_indented_code_blocks: true, space_after_headers: true)
    return markdown.render(text).html_safe
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to 'Home', questions_path %>
    <% if current_user %>
      Signed in as <%= current_user.username %> <%= link_to 'Sign Out', signout_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign In', "/auth/github" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
    <% if @question.errors["title"] %>
      <ul>
        <% @question.errors["title"].each do |error| %>
        <li><%= "Title #{error}" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_field :description %>

    <% if @question.errors["description"] %>
      <ul>
        <% @question.errors["description"].each do |error| %>
        <li><%= "Description #{error}" %></li>
        <% end %>
      </ul>
    <% end %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit</h1>
<%= button_to "Delete this Question", @question, method: :delete %>
<br/>
<%= render "questions/form", question: @question %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |q| %>
  <h3><%= link_to q.title, q %></h3>
<% end %>

<%= link_to 'Submit a Question', new_question_path %>

app/views/questions/new.html.erb
<h1>Submit a Question:</h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<%= markdown(@question.description) %>
Posted by <%= @user.username %> on <%= @question.created_at %>

<% if current_user == @user %>
  <%= button_to "Edit", edit_question_path(@question), method: :get %>
  <%= button_to "Delete", @question, method: :delete %>
<% end %>
<h3>Answers:</h3>

<% if @selected_answer %>
  <div class="accepted-answer">
    <%= markdown(@selected_answer.body) %>
  </div>
<% end %>

<% @answers.each do |answer| %>
    <div class="answer">
      <%= markdown(answer.body) %>
      <% if !@selected_answer && current_user == @user %>
        <%= button_to "Accept Answer", answer, method: :patch %>
      <% end %>
    </div>
<% end %>

<h4>Submit an Answer:</h4>
<%= form_for([@question, @answer]) do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, size: '50x10'%>

    <% if @answer.errors %>
      <ul>
      <% @answer.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    <% end %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>